### ISSUE TITLE
RESTORE_LAST_STATE does not work correctly.

### ISSUE THREAD

**Issue by vishwabmc** [openbmc/skeleton#123] opened 2016-06-30 11:45 UTC
Here is what I tried on Palmetto : 

1/.Set the power policy to RESTORE_LAST_STATE
2/.Power on and it was in HOST_BOOTING state
3/. I went  to PDU and did AC cycle
4/. discover_system_state printed that Last System State was [Host_POWERED_OFF] and stayed there.

I was expecting it to start powering on  since the last known state prior to reset was "Host Booting".

The problem is that discover_system_state look @ system_state" property from "settings" interface and that one always had [Host_Power_off] post a AC cycle. 

We would need to : 
1/. Stop looking at the settings since it will always tell the latest.
2/. Save the last system state somewhere that can be looked into during restore.

**Comment by williamspatrick** [comment] 2016-09-12 02:31
Duplicate of openbmc/openbmc#196

**Closed as completed by williamspatrick** 2016-09-12 02:31 UTC
