### ISSUE TITLE
BMC keep in BMC_STARTING2 state

### ISSUE THREAD

**Issue by Kenthliu** [openbmc/skeleton#78] opened 2016-05-11 03:11 UTC
We found the symptom after AC cycle sometimes.
Attach the journctl log.
[UUT10.txt](https://github.com/openbmc/skeleton/files/258504/UUT10.txt)

**Comment by nkskjames** [comment] 2016-05-11 12:21
This system has thousands of event logs.  It is not getting to BMC_STARTING2 because the fan control is not starting and that is listed as a requirement:
    'BMC_STARTING2' : {
        '/org/openbmc/control/fans' : 0,
        '/org/openbmc/control/chassis0': 0,
    },

But the root of the issue is the event logs.   We need to understand why this hardware has so many.   This is same root cause as https://github.com/openbmc/openbmc/issues/257

**Comment by Kenthliu** [comment] 2016-05-16 08:30
The event is come from HDD info. Every AC cycle will add and tell user how many HDD detect. The SEL quantity should not impact initail. Some events are normal, and sometime SEL full is normal.

**Comment by williamspatrick** [comment] 2016-05-26 03:29
Seems to be a dupe of openbmc/openbmc#257.  Please re-open if you disagree.

**Closed as completed by williamspatrick** 2016-05-26 03:29 UTC
